version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # AWS_ACCOUNT_ID aur AWS_DEFAULT_REGION environment variables CodeBuild mein pehle se hote hain
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/my-frontend-app
      # CODEBUILD_RESOLVED_SOURCE_VERSION se hum commit hash lete hain, taake har image unique ho
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      # Yeh file CodePipeline ko batati hai ke konsi image ECS par deploy karni hai
      - printf '[{"name":"my-frontend-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
